project:
  type: website
  output-dir: docs
website:
  title: "myDigitalAgeWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
  page-footer: 
    left: "Copyright 2022, Joshua De La Torre" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
